spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorzhang929/config-repository
          search-paths: /cloud-server
          username: victorzhang929
          password: yourpassword
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 6002

management:
  endpoints:
    web:
      exposure:
        include: ["info", "health", "refresh"]