spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorzhang929/config-repository
          search-paths: /cloud-server
          username: victorzhang929
          password: yourpassword

server:
  port: 6002