spring:
  application:
    name: eureka-provider
  profiles:
    active: provider-one

---
server:
  port: 9000

eureka:
  instance:
  client:
    fetch-registry: true
    register-with-eureka: true
    #client间隔多长时间去拉去Server服务信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://peer-one:8001/eureka/
spring:
  profiles: provider-one

---

server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    #client间隔多长时间去拉去Server服务信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://peer-one:8002/eureka/
spring:
  profiles: provider-two