spring:
  application:
    name: eureka-provider
  profiles:
    active: singleton

server:
  port: 5001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    #client间隔多长时间去拉去Server服务信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:5004/eureka/
